# Generated by Django 5.2.13 on 2026-05-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_deck_owner_alter_card_deck_cardprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
