# Generated by Django 5.2.13 on 2026-05-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_deck_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprogress',
            name='learning_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
