# Generated by Django 5.2.13 on 2026-05-13 09:59

from django.db import migrations

def mark_shared_decks_as_default(apps, schema_editor):
    Deck = apps.get_model("app", "Deck")
    Deck.objects.filter(owner_id__isnull=True).update(is_default=True)


def unmark_shared_decks_as_default(apps, schema_editor):
    Deck = apps.get_model("app", "Deck")
    Deck.objects.filter(owner_id__isnull=True).update(is_default=False)

class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_cardprogress_learning_step"),
    ]

    operations = [
        migrations.RunPython(
            mark_shared_decks_as_default,
            unmark_shared_decks_as_default,
        ),
    ]
